# Generated by Django 2.1.5 on 2020-05-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=255)),
                ('vehicle_type', models.CharField(default='', max_length=255)),
                ('license_plate_number', models.CharField(default='', max_length=20)),
                ('maximum_passengers', models.IntegerField(default=0)),
                ('special_vehicle_info', models.TextField(blank=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
