# Generated by Django 2.1.5 on 2020-05-16 19:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=1023)),
                ('required_arrival_time', models.DateTimeField()),
                ('passenger_number_from_owner', models.IntegerField()),
                ('passenger_number_in_total', models.IntegerField()),
                ('ride_status', models.CharField(default='open', max_length=255)),
                ('requested_vehicle_type', models.CharField(blank=True, max_length=255)),
                ('special_request', models.TextField(blank=True)),
                ('can_be_shared', models.BooleanField(default=False)),
                ('sharer_id_and_passenger_number_pair', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_owner', to=settings.AUTH_USER_MODEL)),
                ('sharers', models.ManyToManyField(blank=True, related_name='rides_as_sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
